#! /bin/bash
#
# msgserverd          Start/Stop the msgserverd daemon.
#
# chkconfig: 3 90 60
# description: This service accepts connections from client sockets
#	       and process the messages received from the clients
# processname: msgserverd
# config: /opt/msgserverd/etc/msgserverd.conf
# pidfile: /opt/msgserverd/var/run/msgserverd.pid

# Source function library.
. /etc/init.d/functions
 
# See how we were called.

#export MSGSERVER_HOME=/opt/msgserverd/
export MSGSERVER_HOME=/home/msgserver/MessagingServer/

su - msgserver -c "$MSGSERVER_HOME/scripts/servicemsgserverd $1" 
exit
